project:
  type: website
  output-dir: docs

website:
  title: "Prospect Research Toolkit"
  description: A prospect research resource library created by Greg Brooks and Apra Utah
  site-url: https://aprautah.github.io/ProspectResearchToolkit/
  open-graph: true

  announcement: 
    content: "**Welcome!** - this website is a work in progress, and some pages/features may be empty, unfinished, or broken. Thank you for your patience!" 
    position: below-navbar 
    type: info
    icon: info-square-fill

  reader-mode: false
  page-footer: 
    left: "Created by Greg Brooks, in association with Apra Utah"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: index.qmd
      - href: about.qmd
      - section: "Tools"
      - href: toolkit_dashboard1.qmd
      - href: templates.qmd
      - section: "Tutorials & Blog"
        contents: 
          - tutorials.qmd
          - blog.qmd
      - section: "External Resources"
        contents:
          - free_resources_links.qmd

format:
  html:
    respect-user-color-scheme: true
    theme: simplex

    css: styles.css
    toc: true



