project:
  type: website
  output-dir: docs

website:
  title: "Prospect Research Toolkit"
  description: A prospect research resource library created by Greg Brooks and Apra Utah
  site-url: https://aprautah.github.io/ProspectResearchToolkit/
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: tutorials.qmd
        text: Tutorials
      - href: blog.qmd
        text: Blog

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: united
      dark: darkly

    css: styles.css
    toc: true



