project:
  type: website
  output-dir: docs

website:
  title: "Prospect Research Toolkit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: tutorials.qmd
        text: Tutorials
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



