project:
  type: website
  output-dir: docs

website:
  title: "Prospect Research Toolkit"
open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



