---
title: "Welcome!"
---
# Overview
This is an online research toolkit, taking inspiration from [Bellingcat's Online Investigative Toolkit](https://bellingcat.gitbook.io/toolkit){.external} as a way to establish a community-driven library of helpful resources. Bellingcat's toolkit is intended for investigative journalists, a world not disimilar to our own as prospect researchers, so it serves as a solid touchstone.

# Goals
Create high quality prospect research education and tools available to big shops and small shops alike.

## Short-term
- Synthetic donor dataset for training, examples, and presentations
- AI Prompt library and use-cases, as well as "helper files" for creating stronger research posture without having to initialize an entire agent
- Software tool comparisons, paid and free
- Templates and tutorials

## Long-term
- Extensions or add-ins, or community plugins (potentially starting with Obsidian or Excel)
- Standalone app that integrates with free and paid tools
- Collaboration with other Apra chapters and Apra International

# Tutorials & Docs I'm learning from:
- [Quarto-the definitive guide](https://quarto-tdg.org/){.external}
- [Quarto docs](https://quarto.org/docs/websites) {.external}
- [Set-up tutorial by Dan Yavorksy](https://www.danyavorsky.com/posts/020-quarto-websites/){.external}
