let
    Source = Csv.Document(File.Contents("C:\Users\u1428176\Downloads\prospdev_filterraw.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sector", type text}, {"title_cleaned", type text}, {"frequency_cleaned", Int64.Type}, {"title_generalized", type text}, {"frequency_generalized", Int64.Type}, {"title_simplified", type text}, {"frequency_simplified", Int64.Type}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each not Text.Contains([title_cleaned], "Sales") or not Text.Contains([title_cleaned], "Commercial")),
    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each Text.Contains([title_cleaned], "Prospect")),
    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each not Text.Contains([title_cleaned], "Business")),
    #"Filtered Rows3" = Table.SelectRows(#"Filtered Rows2", each not Text.Contains([title_cleaned], "Sales") or not Text.Contains([title_cleaned], "B2B")),
    #"Filtered Rows4" = Table.SelectRows(#"Filtered Rows3", each ([title_cleaned] <> "Account Prospecting Manager" and [title_cleaned] <> "B2B Prospecting Manager")),
    #"Filtered Rows5" = Table.SelectRows(#"Filtered Rows4", each not Text.Contains([title_cleaned], "Client")),
    #"Filtered Rows6" = Table.SelectRows(#"Filtered Rows5", each not Text.Contains([title_cleaned], "Classroom") or not Text.Contains([title_cleaned], "International")),
    #"Filtered Rows7" = Table.SelectRows(#"Filtered Rows6", each ([title_cleaned] <> "Commercial Prospecting Assistant" and [title_cleaned] <> "Commercial Prospecting Intern" and [title_cleaned] <> "Commercial Prospecting Internship" and [title_cleaned] <> "Commercial Prospecting Manager" and [title_cleaned] <> "Commercial Prospecting Officer" and [title_cleaned] <> "Commercial Prospecting Trainee" and [title_cleaned] <> "Consulting Prospect Researcher" and [title_cleaned] <> "Contract Prospect Researcher" and [title_cleaned] <> "Corporate Prospect Researcher" and [title_cleaned] <> "Corporate Prospecting Intern" and [title_cleaned] <> "Customer Prospecting Assistant" and [title_cleaned] <> "Customer Prospecting Officer" and [title_cleaned] <> "Customer Prospecting Specialist" and [title_cleaned] <> "Educational Prospecting Director" and [title_cleaned] <> "Electoral Prospecting Deputy Director" and [title_cleaned] <> "Employment Prospecting Coordinator" and [title_cleaned] <> "Employment Prospecting Technical Coordinator" and [title_cleaned] <> "Employment Prospector Technician" and [title_cleaned] <> "Export Prospecting Officer" and [title_cleaned] <> "Food Prospective Coordinator" and [title_cleaned] <> "Foreign Investment Prospection Assistant" and [title_cleaned] <> "Foreign Market Prospecting Advisor" and [title_cleaned] <> "Foreign Trade Prospector" and [title_cleaned] <> "Hotel Prospecting Manager" and [title_cleaned] <> "International Prospecting Intern" and [title_cleaned] <> "International Prospecting Manager" and [title_cleaned] <> "International Prospection Intern" and [title_cleaned] <> "International Prospection Officer" and [title_cleaned] <> "International Trader Prospecting Intern" and [title_cleaned] <> "Market Prospection Specialist" and [title_cleaned] <> "Marketing Department Prospecting Internship" and [title_cleaned] <> "Marketing Prospects Officer" and [title_cleaned] <> "Minas Gerais Financial Systems Opportunity Prospecting Network Coordinator" and [title_cleaned] <> "Mission Prospective Officer" and [title_cleaned] <> "Partnership Prospection Specialist" and [title_cleaned] <> "Prospect Analysis Director" and [title_cleaned] <> "Prospect Analytics Director" and [title_cleaned] <> "Prospect Data Manager" and [title_cleaned] <> "Prospect Program Assistant" and [title_cleaned] <> "Prospect Records Assistant" and [title_cleaned] <> "Prospect Sales Coordinator" and [title_cleaned] <> "Prospect Service Analyst" and [title_cleaned] <> "Prospecting Charge Intern" and [title_cleaned] <> "Prospecting Commercial Assistant" and [title_cleaned] <> "Prospection Mission Manager" and [title_cleaned] <> "Prospection Mission Officer" and [title_cleaned] <> "Prospection Officer" and [title_cleaned] <> "Prospective Analysis Group Advisor" and [title_cleaned] <> "Prospective Board Member" and [title_cleaned] <> "Prospective Classroom Teacher" and [title_cleaned] <> "Prospective Department Manager" and [title_cleaned] <> "Prospective Mission Head" and [title_cleaned] <> "Prospective Mission Officer" and [title_cleaned] <> "Prospective Municipal Secretary" and [title_cleaned] <> "Prospective Office Head" and [title_cleaned] <> "Prospective Political Scenarios Seminar Tutor" and [title_cleaned] <> "Prospective Relationship Manager" and [title_cleaned] <> "Prospective Section Vice President" and [title_cleaned] <> "Prospective Senior Policy Officer" and [title_cleaned] <> "Prospective Service Head" and [title_cleaned] <> "Prospective Service Mission Manager" and [title_cleaned] <> "Prospective Student Advisor" and [title_cleaned] <> "Prospective Student Ambassador" and [title_cleaned] <> "Prospective Student Caller" and [title_cleaned] <> "Prospective Student Coach" and [title_cleaned] <> "Prospective Student Counselor" and [title_cleaned] <> "Prospective Student Host" and [title_cleaned] <> "Prospective Student Liaison" and [title_cleaned] <> "Prospective Student Overnight Host" and [title_cleaned] <> "Prospective Student Relations Assistant" and [title_cleaned] <> "Prospective Student Service Director" and [title_cleaned] <> "Prospective Student Service Officer" and [title_cleaned] <> "Prospective Student Tour Guide" and [title_cleaned] <> "Prospective Students Advisor" and [title_cleaned] <> "Prospective Students Career Counselor" and [title_cleaned] <> "Prospective Studies Officer" and [title_cleaned] <> "Prospective Unit Manager" and [title_cleaned] <> "Prospector" and [title_cleaned] <> "Sales Prospecting Assistant" and [title_cleaned] <> "Sales Prospecting Intern" and [title_cleaned] <> "Sales Prospecting Research Assistant" and [title_cleaned] <> "Sales Prospecting Specialist" and [title_cleaned] <> "Sales Prospection Assistant" and [title_cleaned] <> "Sales Prospection Internship" and [title_cleaned] <> "Strategic Prospective Consultant" and [title_cleaned] <> "Technological Prospecting Deputy Director" and [title_cleaned] <> "Territorial Prospective Mission Officer" and [title_cleaned] <> "Territorial Prospective Studies Officer" and [title_cleaned] <> "Young Prospects Project Manager" and [title_cleaned] <> "Youth Prospectus Officer"))
in
    #"Filtered Rows7"
