---
title: "Quarto Resources"
author: Greg Brooks
date: 10-14-2025
---

# Resources being used to build this website

## Tutorials & Docs being used to create this website
- [Quarto docs](https://quarto.org/docs/websites){.external}
- [Set-up tutorial by Dan Yavorksy](https://www.danyavorsky.com/posts/020-quarto-websites/){.external}
- [Documentation philosophy](https://diataxis.fr/){.external}
- [Quarto docs, another way to read them](https://deepwiki.com/quarto-dev/quarto-web/4.1-website-navigation){.external}
- [Images and design inspiration from Cynthia Huang](https://www.cynthiahqy.com/blog.html){.external}
- [Quarto curated Github resources](https://github.com/mcanouil/awesome-quarto){.external}
- Toolkit structure aiming to take notes from [Bellingcat's Online Investigative Toolkit](https://bellingcat.gitbook.io/toolkit){.external} as a way to establish a community-driven library of helpful resources. Bellingcat's toolkit is intended for investigative journalists, a world not disimilar to our own as prospect researchers, so it serves as a solid touchstone. 
- [Dr. Mickaël CANOUIL is a Quarto extension rockstar, scientist, and writes really clear tutorials](https://mickael.canouil.fr/posts/2025-05-19-quarto-codespaces/)
- ["Mastering Data Visualization using R, Quarto, and the Tidyverse" - all tools I love](https://data-vis-using-r.info/03_intro_to_quarto/intro_to_quarto.html)
- [very helpful example of quarto details like relative paths](https://quarto.neocities.org/docs/relative_paths)

## dashboards
- [example from UCSB](https://learning.nceas.ucsb.edu/2024-03-ucsb-faculty/session_10.html)
- [Quarto dashboard lecture](https://vizdata.org/slides/20/20-quarto-dashboards.html#/qmd-dashboard)
- [Shinylive + Quarto for interactivity that doesn't rely on server](https://quarto.thecoatlessprofessor.com/r-shinylive-demo/)
- [More dashboard docs](https://quarto.org/docs/dashboards/data-display.html)

## synthetic dataset creation (for example donor dataset)
- [very basic method in R](https://www.geeksforgeeks.org/r-language/how-to-create-a-custom-synthetic-dataset-in-r/)
- [more complex method](https://andreashandel.github.io/MADAcourse/content/module-synthetic-data/synthetic-data-new-r/synthetic-data-new-r.html)
